### ISSUE TITLE
RT3S: Channel Selector delayed input

### ISSUE THREAD

**Issue by marcoSchr** [OpenRTX/OpenRTX#137]
When turning the channel selector, the device sometimes takes some time to register the input.
~~When turning the volume knob the volume changes very delayed or not at all.~~

# Expected behavior:
- When turning the channel selector the next channel is selected
- ~~When turning the volume knob, the volume is changed instantly~~

#  Observed behavior:
- Turning the channel selector sometimes does nothing until, turning it again, then it skips 1 channel
- ~~Turning the volume knob only changes the volume up, when turning it about 3/4, but it does not change to a lower volume , when turning the knob to nearly the off position~~

# Steps to reproduce:

## Channel selector
1. Turn the device on
2. Press the red button to be in channel mode on channel 1
3. Turn the channel selector 1 position
4. The channel does not change to channel 2
5. Turn the channel selector 1 position
6. The channel changes to channel 3

## ~~Volume knob~~
1. ~~Turn the device on~~
2. ~~Turn the squelch off~~
3. ~~turn the volume up~~
4. ~~When the knob is turned about 3/4 all the way the volume will switch to loud~~
5. ~~turn the volume knob to the minimum position before off~~
6. ~~The volume stays loud~~

# Additional Information

Device: Retevis RT3S
Firmware: 0.3.5
Production date: 08 2022

When using the stock firmware, the channel selector instantly changes channel and the volume knob instantly changes the volume.

**Comment by silseva** [comment]
Hi!
Thank you for reporting, these issues are going to be solved as soon as we set up a proper event exchange system in the firmware (which I hope is going to happen soon).

**Comment by marcoSchr** [comment]
The Volume knob issue is fixed by commit 5ea94ee1afcba5f9a3d70eee380a8fa10baa93b0 and dd46a48cd1526582b32cb331f70b5af6041270b7.

**Comment by chrisdebian** [comment]
So it looks like the channel selector is still an issue. Given the age of this issue, can anyone confirm it's still a problem?

**Comment by silseva** [comment]
Yes, it is still an issue. It requires an improvement in how the input events are managed, but this will be done at a later stage.
